#############################################################################################################################################
#                                                                                                                                           #
#   .d8888b.                             d8b  .d888                 d8888          888    d8b  .d8888b.  888                        888     #
#  d88P  Y88b                            Y8P d88P"                 d88888          888    Y8P d88P  Y88b 888                        888     #
#  888    888                                888                  d88P888          888        888    888 888                        888     #
#  888         .d88b.   .d88b.  88888b.  888 888888 888  888     d88P 888 88888b.  888888 888 888        88888b.   .d88b.   8888b.  888888  #
#  888        d88""88b d88P"88b 888 "88b 888 888    888  888    d88P  888 888 "88b 888    888 888        888 "88b d8P  Y8b     "88b 888     #
#  888    888 888  888 888  888 888  888 888 888    888  888   d88P   888 888  888 888    888 888    888 888  888 88888888 .d888888 888     #
#  Y88b  d88P Y88..88P Y88b 888 888  888 888 888    Y88b 888  d8888888888 888  888 Y88b.  888 Y88b  d88P 888  888 Y8b.     888  888 Y88b.   #
#   "Y8888P"   "Y88P"   "Y88888 888  888 888 888     "Y88888 d88P     888 888  888  "Y888 888  "Y8888P"  888  888  "Y8888  "Y888888  "Y888  #
#                           888                          888                                                                                #
#                      Y8b d88P                     Y8b d88P                                                                                #
#                       "Y88P"                       "Y88P"                                                                                 #
#                                                                                                                                           #
#############################################################################################################################################
#                                                                settings.yml                                                               #
#                                                                                                                                           #
#                                                                                                                                           #
#                                                           Powered By CognifyDev                                                           #
#                                                                Made With ❤                                                               #
#                                                                                                                                           #
#                                                                                                                                           #
#                                                                                                                                           #
#############################################################################################################################################

# WARNING: THIS ANTI-CHEAT ONLY SUPPORT VANILLA AMONG US CLIENTS
# BECAUSE THE MOD ROOMS USUALLY ARE PRIVATE.

check-settings:
  # Should we kick those who are checked as 'hackers'?
  kick: true
  
  # Should we ban those who are checked as 'hackers'?
  ban: false
  
  # Should we add them to the blacklist when they are marked as 'hackers'?
  add-to-blacklist: true
  
  # Should we cancel the unfair actions?
  cancelled: true

# Options Description
# enable => should we enable them?
# max-violations => the max violations that are allowed
# Usually violations will add 1 when the player is checked as a hacker.
# If you cannot understand them clearly, please do not change them.

checks:
  # This will check those players who use AUM & SickoMenu
  BadPacketsA:
    enable: true
    max-violations: 1
  # This will check those who report at wrong time.
  IllegalReportA:
    enable: true
    max-violations: 2